# -*- coding: utf-8 -*-
"""Santa Foraging Expedition - Sean Collins

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CcFB2-xtFj1DtVlTHZc5-NBwmbJJXvTV
"""

import os
import shutil

myfile = "/Users/seancollins/Downloads/09-25_input-1.txt"
os.path.isfile(myfile)

file1 = open("09-25_input-1.txt", 'r')